### ISSUE TITLE
about casket_id

### ISSUE THREAD

**Issue by feeops** [Andrew3019/CSGO-Storage-Unit#1]
where can I find casket_id?

if I have a lot of casket，How can I process with them?

**Comment by Andrew3019** [comment]
> where can I find casket_id?
> 
> if I have a lot of casket，How can I process with them?

Hello, not that it pertains to anything in this repository, but I can give you a code snippet I use to find my caskets:

```
csgo.inventory.filter(item => ('casket_contained_item_count' in item)).forEach(function(i) {
  console.log('\t' + i['custom_name'] + ": " + i['casket_contained_item_count'] + '\t(' + i['id'] + ')');
})
```

**Comment by feeops** [comment]
thanks.It does work.

I have run this code

> let inventory = csgo.inventory;
  let currentTime = new Date().getTime();
  let cnt = 0;
  console.log(inventory.length);

But inventory.length is 1035.I thought the length is less than 1000.
Why?

**Comment by Andrew3019** [comment]
csgo.inventory will sometimes load items that are inside storage units. I believe you can filter these items out by checking if they have a "casket_id" key in the dict.

**Comment by feeops** [comment]
thanks.
