### ISSUE TITLE
about removeFromCasket

### ISSUE THREAD

**Issue by feeops** [Andrew3019/CSGO-Storage-Unit#2]
I have a lot of storage unit,about 10k items.

I used removeFromCasket function.

It printed "removed 50 items from storage units"

But my main inventory only added 10 items.

Was anything wrong?

**Comment by feeops** [comment]
I  add some time sleep.
It works now

**Comment by Andrew3019** [comment]
Yes, I believe the new ratelimit update after CS2 was announced changed storage unit max rate to 10 items / second.
